### ISSUE TITLE
Error computing in lingam

### ISSUE THREAD

**Issue by HYeCao** [jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization#2]
Great work, and thank you for sharing the code. We encountered some errors while running the code with the default settings. Are these errors reasonable, and will they affect the calculation of causality?

home/chy/code/causalRL/ace/causallearnmain/causallearn/search/FCMBased/lingam/direct_lingam.py:150: RuntimeWarning: divide by zero encountered in divide
  return (self._entropy(xj_std) + self._entropy(ri_j / np.std(ri_j))) - \
/home/chy/anaconda3/envs/ace/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py:2306: RuntimeWarning: divide by zero encountered in log
  n_samples * np.log(2 * np.pi * self.noise_variance_)                                                                                               
/home/chy/anaconda3/envs/ace/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py:2307: RuntimeWarning: invalid value encountered in divide
  + residuals_sum_squares / self.noise_variance_                                                                                                       
/home/chy/anaconda3/envs/ace/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py:2306: RuntimeWarning: divide by zero encountered in log
  n_samples * np.log(2 * np.pi * self.noise_variance_)                                                                                                 
/home/chy/anaconda3/envs/ace/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py:2307: RuntimeWarning: invalid value encountered in divide
  + residuals_sum_squares / self.noise_variance_                                                                                                       
/home/chy/anaconda3/envs/ace/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py:2306: RuntimeWarning: divide by zero encountered in log  
  n_samples * np.log(2 * np.pi * self.noise_variance_)  
  
  
![image](https://github.com/jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization/assets/37492613/1b9c9c7b-6ed1-4812-bc32-e63adb5c9c23)

**Comment by YanaZeng** [comment]
Hi, HYeCao. Thanks so much for your interest in our work.

These error messages you encountered likely indicate that the noise variance is too small, approaching zero. This issue generally would not impact the overall calculations much. However, to avoid such problems, you could try setting a minimum threshold for the noise variance, such as 1e-8. This will help prevent division by zero errors.
