### ISSUE TITLE
Question about the experiments

### ISSUE THREAD

**Issue by HYeCao** [jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization#3]
When reproducing experimental environments such as walker2d, pick place wall, etc., we have observed significant discrepancies between our results and those reported in the papers. What could be causing this issue?

**Comment by cheryyunl** [comment]
Hi here is some of our experiment data on pick-place-wall (CausalSAC with reset). In some seeds, the agent will fail. 
<img width="867" alt="image" src="https://github.com/jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization/assets/40263198/bc73cc28-a8d0-488f-8e79-7311436f4fa4">

Please check your MetaWorld and Gym version, also the reward and state type. We will check our metaworld wrapper again.

**Comment by cheryyunl** [comment]
Hi here is some of our experiment data on pick-place-wall. In some seeds, the agent may fail. (DrmCAC=ACE and DrmCBAC=ACE+BEE)
<img width="820" alt="image" src="https://github.com/jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization/assets/40263198/c85cf79c-e00c-47ae-bfc9-2d5bed6c6cde">
Please check your MetaWorld and Gym version, also the reward and state type. We will check the metaworld wrapper again.

**Comment by jity16** [comment]
Here is the a snapshot of our WandB dashboard for the walker2d -v2 environment, without any smoothing techniques. Some suggestions on HPs that may enhance the performance in walker2d-v2, try "batch_size: 256, updates_per_step: 1, target_update_interval: 1, hidden_size: 256"
<img width="1119" alt="image" src="https://github.com/jity16/ACE-Off-Policy-Actor-Critic-with-Causality-Aware-Entropy-Regularization/assets/35065354/809feec0-0999-4e5b-a8e0-71d7770f642d">

**Comment by HYeCao** [comment]
Thank you very much for your reply. I will try it again by your HPs.
Can you provide a complete settings of HPs in different environments and tasks?

**Comment by cheryyunl** [comment]
update experiment curves
